apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ems-secrets-with-kv
spec:
  provider: azure
  secretObjects:
  - secretName: tls-secret
    type: kubernetes.io/tls
    data:
    - objectName: backend
      key: tls.crt
    - objectName: backend
      key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: ""  # Set the clientID of the user-assigned managed identity to us
    keyvaultName: "<name of your KV>"        
    objects: 
        - |
          objectName: backend 
          objectType: secret

    tenantId: "" #Set the tenant ID of your Azure AD"